/* eslint-disable jsx-a11y/alt-text */
"use client";

import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import { IdeaDetail } from "@/types";

// Register standard fonts
Font.register({
  family: "Helvetica",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
    },
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
      fontWeight: "bold",
    },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 12,
    lineHeight: 1.5,
    color: "#000000",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#000000",
    paddingLeft: 8,
  },
  // Removed 'row' and 'column' styles to favor simple vertical stacking
  infoGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 4,
    marginTop: 8,
  },
  text: {
    fontSize: 10,
    color: "#374151",
    marginBottom: 4,
  },
  boldText: {
    fontWeight: "bold",
    color: "#000000",
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  tag: {
    fontSize: 8,
    padding: "4 8",
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  bulletPoint: {
    flexDirection: "row",
    marginBottom: 2,
  },
  bullet: {
    width: 10,
    fontSize: 10,
  },
  markdownH1: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 5,
  },
  markdownH2: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 8,
    marginBottom: 4,
  },
  markdownH3: {
    fontSize: 12,
    fontWeight: "bold",
    marginTop: 6,
    marginBottom: 3,
  },
});

interface PdfExportTemplateProps {
  idea: IdeaDetail;
}

// Helper to parse inline markdown (currently supports **bold**)
const renderStyledText = (text: string) => {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <Text key={index} style={styles.boldText}>
          {part.slice(2, -2)}
        </Text>
      );
    }
    return <Text key={index}>{part}</Text>;
  });
};

const MarkdownView = ({ content }: { content: string }) => {
  if (!content) return <Text style={styles.text}>No content available</Text>;

  const lines = content.split("\n");
  return (
    <View>
      {lines.map((line, index) => {
        // Headers
        if (line.startsWith("# ")) {
          return (
            <Text key={index} style={styles.markdownH1}>
              {line.replace("# ", "")}
            </Text>
          );
        }
        if (line.startsWith("## ")) {
          return (
            <Text key={index} style={styles.markdownH2}>
              {line.replace("## ", "")}
            </Text>
          );
        }
        if (line.startsWith("### ")) {
          return (
            <Text key={index} style={styles.markdownH3}>
              {line.replace("### ", "")}
            </Text>
          );
        }
        // List items
        if (line.startsWith("- ") || line.startsWith("* ")) {
          return (
            <View key={index} style={styles.bulletPoint}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.text}>
                {renderStyledText(line.replace(/^[-*]\s/, ""))}
              </Text>
            </View>
          );
        }
        // Empty lines
        if (line.trim() === "") return <Text key={index}>{"\n"}</Text>;

        // Regular paragraphs with inline styling
        return (
          <Text key={index} style={styles.text}>
            {renderStyledText(line)}
          </Text>
        );
      })}
    </View>
  );
};

export const PdfExportDocument = ({ idea }: PdfExportTemplateProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* HEADER */}
      <View style={styles.header}>
        <Text style={styles.title}>{idea.title}</Text>
        <Text style={styles.subtitle}>
          Generated by AI Project Architect • {new Date().toLocaleDateString()}
        </Text>
      </View>

      {/* PROJECT OVERVIEW - Stacked Vertically */}
      <View style={styles.section}>
        {/* Problem Statement */}
        <View style={styles.infoGroup}>
          <Text style={styles.sectionTitle}>Problem Statement</Text>
          <Text style={styles.text}>
            {idea.problem_statement || "No problem statement defined."}
          </Text>
        </View>

        {/* Tech Stack */}
        <View style={styles.infoGroup}>
          <Text style={styles.label}>Tech Stack</Text>
          <View style={styles.tagContainer}>
            {idea.tech_stack?.map((tech, i) => (
              <Text key={i} style={styles.tag}>
                {tech}
              </Text>
            ))}
          </View>
        </View>

        {/* Target Audience */}
        <View style={styles.infoGroup}>
          <Text style={styles.label}>Target Audience</Text>
          {idea.target_audience?.map((aud: any, i: number) => (
            <View key={i} style={styles.bulletPoint}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.text}>{aud.text}</Text>
            </View>
          ))}
        </View>
      </View>

      <View
        style={{
          borderBottomWidth: 1,
          borderBottomColor: "#e5e7eb",
          marginVertical: 20,
        }}
      />

      {/* BLUEPRINT CONTENT */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Project Blueprint</Text>
        <MarkdownView content={idea.workbenchContent?.markdown || ""} />
      </View>
    </Page>
  </Document>
);
